/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;
import modeloConection.ConexaoBD;  

public class TelaMenu extends javax.swing.JFrame {
      ConexaoBD conecta = new ConexaoBD () ;
 
    public TelaMenu() {
        initComponents();
        conecta.conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBenvindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMed = new javax.swing.JButton();
        btnPac = new javax.swing.JButton();
        btnEnf = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnFecharBenvindo = new javax.swing.JButton();
        lblFundoMenu = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadMed = new javax.swing.JMenuItem();
        jMenuItemCadPac = new javax.swing.JMenuItem();
        jMenuItemCadEnf = new javax.swing.JMenuItem();
        jMenuItemCadUsu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemTelaBenvindo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBenvindo.setTitle("BEM-VINDO A CLÍNICA GIRASSOL");
        jInternalFrameBenvindo.setVisible(true);
        jInternalFrameBenvindo.getContentPane().setLayout(null);

        jPanelInterno.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabel2.setText("Cadastro -");
        jPanelInterno.add(jLabel2);
        jLabel2.setBounds(0, 0, 70, 14);

        btnMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Group2_Doctor_Nursei.png"))); // NOI18N
        btnMed.setToolTipText("Medicos");
        btnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedActionPerformed(evt);
            }
        });
        jPanelInterno.add(btnMed);
        btnMed.setBounds(0, 20, 80, 60);

        btnPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Use_23096.png"))); // NOI18N
        btnPac.setToolTipText("Pacientes");
        jPanelInterno.add(btnPac);
        btnPac.setBounds(160, 20, 81, 60);

        btnEnf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Group2_Doctor_Patient3.png"))); // NOI18N
        btnEnf.setToolTipText("Enfermeiros");
        jPanelInterno.add(btnEnf);
        btnEnf.setBounds(80, 20, 80, 60);

        btnAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_calendar_285670 (4).png"))); // NOI18N
        btnAgenda.setToolTipText("Angendamento");
        btnAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendaActionPerformed(evt);
            }
        });
        jPanelInterno.add(btnAgenda);
        btnAgenda.setBounds(310, 20, 80, 60);

        jLabel3.setText("Agenda -");
        jPanelInterno.add(jLabel3);
        jLabel3.setBounds(310, 0, 70, 14);

        jInternalFrameBenvindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 20, 620, 140);

        jLabel1.setText("Sistema de gerenciamento de:");
        jInternalFrameBenvindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 190, 14);

        btnFecharBenvindo.setText("Fechar");
        btnFecharBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharBenvindoActionPerformed(evt);
            }
        });
        jInternalFrameBenvindo.getContentPane().add(btnFecharBenvindo);
        btnFecharBenvindo.setBounds(535, 0, 90, 23);

        getContentPane().add(jInternalFrameBenvindo);
        jInternalFrameBenvindo.setBounds(0, 250, 640, 180);

        lblFundoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clinica girassol.jpg"))); // NOI18N
        getContentPane().add(lblFundoMenu);
        lblFundoMenu.setBounds(0, 0, 640, 430);

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemCadMed.setText("Medicos");
        jMenuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadMed);

        jMenuItemCadPac.setText("Pacientes");
        jMenu1.add(jMenuItemCadPac);

        jMenuItemCadEnf.setText("Enfermeiros");
        jMenu1.add(jMenuItemCadEnf);

        jMenuItemCadUsu.setText("Usuarios");
        jMenu1.add(jMenuItemCadUsu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorios");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        jMenuItemTelaBenvindo.setText("Tela-Bem-vindo");
        jMenuItemTelaBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBenvindoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemTelaBenvindo);

        jMenuBar1.add(jMenu3);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(655, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnFecharBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharBenvindoActionPerformed
        // TODO add your handling code here:
        jInternalFrameBenvindo.dispose();
        
    }//GEN-LAST:event_btnFecharBenvindoActionPerformed

    private void jMenuItemTelaBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBenvindoActionPerformed
        // TODO add your handling code here:
        TelaMenu ben = new TelaMenu ();
        ben.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItemTelaBenvindoActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedActionPerformed
        // TODO add your handling code here:
         FormMedico med = new FormMedico();
        med.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadMedActionPerformed

    private void btnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedActionPerformed
        // TODO add your handling code here:
        FormMedico med = new FormMedico();
        med.setVisible(true);
    }//GEN-LAST:event_btnMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnEnf;
    private javax.swing.JButton btnFecharBenvindo;
    private javax.swing.JButton btnMed;
    private javax.swing.JButton btnPac;
    private javax.swing.JInternalFrame jInternalFrameBenvindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadEnf;
    private javax.swing.JMenuItem jMenuItemCadMed;
    private javax.swing.JMenuItem jMenuItemCadPac;
    private javax.swing.JMenuItem jMenuItemCadUsu;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBenvindo;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInterno;
    private javax.swing.JLabel lblFundoMenu;
    // End of variables declaration//GEN-END:variables
}
